version: '3.8'

services:
  # Development API with hot reload
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: cooking-api-dev
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      PORT: 3000
      # Supabase Database URL (replace with your Supabase connection string)
      DATABASE_URL: postgresql://postgres:[password]@db.[project-ref].supabase.co:5432/postgres
      JWT_SECRET: dev-jwt-secret-change-me
      JWT_EXPIRES_IN: 7d
      GOOGLE_CLIENT_ID: your-google-client-id
      GOOGLE_CLIENT_SECRET: your-google-client-secret
      CLOUDINARY_CLOUD_NAME: your-cloudinary-cloud-name
      CLOUDINARY_API_KEY: your-cloudinary-api-key
      CLOUDINARY_API_SECRET: your-cloudinary-api-secret
      CORS_ORIGIN: http://localhost:3000
      # Supabase specific
      SUPABASE_URL: https://[project-ref].supabase.co
      SUPABASE_ANON_KEY: your-supabase-anon-key
      SUPABASE_SERVICE_KEY: your-supabase-service-key
    volumes:
      # Mount source code for hot reload
      - ./src:/app/src:ro
      - ./prisma:/app/prisma:ro
      - ./package.json:/app/package.json:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      # Exclude node_modules from host (use container's version)
      - /app/node_modules
      # Mount uploads directory
      - ./uploads:/app/uploads
    networks:
      - cooking-network
    # Add health check for development
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s



networks:
  cooking-network:
    driver: bridge