version: '3.8'

services:
  # Production API Application (built and optimized)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cooking-api-prod
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      PORT: 3000
      # Supabase Database URL (replace with your Supabase connection string)
      DATABASE_URL: postgresql://postgres:[password]@db.[project-ref].supabase.co:5432/postgres
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRES_IN: 7d
      GOOGLE_CLIENT_ID: your-google-client-id
      GOOGLE_CLIENT_SECRET: your-google-client-secret
      CLOUDINARY_CLOUD_NAME: your-cloudinary-cloud-name
      CLOUDINARY_API_KEY: your-cloudinary-api-key
      CLOUDINARY_API_SECRET: your-cloudinary-api-secret
      CORS_ORIGIN: http://localhost:3000
      # Supabase specific
      SUPABASE_URL: https://[project-ref].supabase.co
      SUPABASE_ANON_KEY: your-supabase-anon-key
      SUPABASE_SERVICE_KEY: your-supabase-service-key
    volumes:
      - ./uploads:/app/uploads
    networks:
      - cooking-network
    profiles:
      - production
